databases:
  - name: todo-db
    databaseName: todo_db
    user: todo_user
    plan: free

services:
  - type: web
    name: todo-django-htmx
    runtime: docker
    startCommand: "gunicorn app.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
